Correct port conflict
> ERROR: for simulateur_nginx_1  Cannot start service nginx: driver failed programming external connectivity on endpoint simulateur_nginx_1 (a55cb1b1911fa95170641d9af779861afa85aed0034e0c3fd23baf117e829730): Bind for 0.0.0.0:8080 failed: port is already allocated